### ISSUE TITLE
Using a wildcard argument matcher inside a block given to #stub or #mock doesn't seem to work

### ISSUE THREAD

**Issue by mcmire** [rr/rr#10]
See https://github.com/btakita/rr/issues/93.

**Comment by sandstrom** [comment]
@mcmire is this issue still relevant? Otherwise, perhaps we can close it, it's quite old. Closing old issues helps focusing on relevant/existing problems. Can re-open if other people have this issue.

cc @kou

**Comment by mcmire** [comment]
Potentially, but I'm fine with this being closed unless there are any objections.

**Comment by kou** [comment]
The block for `mock` is evaluated int the context of the created mock. It means that `anything` is processed as a new mocked method. We need to refer `anything` provided by RR in the block:

```ruby
require 'minitest/autorun'
require 'rr'

class FooTest < MiniTest::Unit::TestCase
  include RR::Adapters::MiniTest

  attr_reader :object

  def setup
    @object = Object.new
  end

  def test_foo
    anything_ = anything
    mock(object) do
      baz(anything_).once
    end
    object.baz('whatever')
  end
end
```
