### ISSUE TITLE
[*foo] idiom fails on ruby 1.9.2 with rr stubs/mocks

### ISSUE THREAD

**Issue by mcmire** [rr/rr#11]
See https://github.com/btakita/rr/issues/61.

Not sure of a good solution just yet.

**Comment by sandstrom** [comment]
@mcmire is this issue still relevant? Otherwise, perhaps we can close it, it's quite old. Closing old issues helps focusing on relevant/existing problems. Can re-open if other people have this issue.

cc @kou

**Comment by mcmire** [comment]
Potentially, but I'm fine with this being closed unless there are any objections.

**Comment by kou** [comment]
It seems that this has been fixed in master:

```ruby
require 'rr'
include RR::DSL
o = Object.new
stub(o).foo{"foo"}
[*o]
```

```console
$ ruby -v /tmp/a.rb
ruby 2.8.0dev (2020-05-14T08:19:39Z master 336119dfc5) [x86_64-linux]
```
