### ISSUE TITLE
any_instance_of stubs failing with class hierarchies

### ISSUE THREAD

**Issue by mcmire** [rr/rr#12]
See https://github.com/btakita/rr/pull/70.

**Comment by sandstrom** [comment]
@mcmire is this issue still relevant? Otherwise, perhaps we can close it, it's quite old. Closing old issues helps focusing on relevant/existing problems. Can re-open if other people have this issue.

cc @kou

**Comment by mcmire** [comment]
Potentially, but I'm fine with this being closed unless there are any objections.

**Comment by kou** [comment]
I've fixed.
