### ISSUE TITLE
JRuby specs take forever to run

### ISSUE THREAD

**Issue by mcmire** [rr/rr#28]
Not a huge concern but this just irks me.

**Comment by sandstrom** [comment]
@mcmire is this issue still relevant? Otherwise, perhaps we can close it, it's quite old. Closing old issues helps focusing on relevant/existing problems. Can re-open if other people have this issue.

cc @kou

**Comment by mcmire** [comment]
I'm fine with this being closed unless there are any objections.

**Comment by kou** [comment]
Closing.
We'll drop RSpec based tests because we can't maintain them.
