### ISSUE TITLE
Support RSpec 3

### ISSUE THREAD

**Issue by dschweisguth** [rr/rr#56]
In my brief experiment changing the RSpec2 adapter to match an RSpec version beginning with 2 or 3 was all that was needed. I didn't run rr's tests, though. An unrelated issue will keep me at RSpec 2.99 for now, so I thought I'd see if anyone else wanted to do that first.

**Comment by kou** [comment]
Sorry. We'll remove RSpec support.
Please use rspec-mock or test-unit instead.
