### ISSUE TITLE
Stop supporting Ruby 1.8

### ISSUE THREAD

**Issue by mcmire** [rr/rr#6]
Even though 1.8 has basically been end-of-lifed, I don't want to remove support for it in a 1.x release. We should probably wait until all of the major bugs have been fixed and then we can cut a 2.0 release that addresses this issue.

**Comment by sandstrom** [comment]
@mcmire is this issue still relevant? I think support is limited to ruby 2.4 and higher now. Can we close this?

cc @kou

**Comment by mcmire** [comment]
Yeah, I think we can definitely close this one, unless there are any objections.

**Comment by kou** [comment]
Closing.
