### ISSUE TITLE
OpenStruct with Ruby 2.3.1

### ISSUE THREAD

**Issue by arthurlm44** [rr/rr#64]
When attempting to upgrade to ruby-2.3.1 from ruby-2.2.3, I am running into this identical issue:
[OpenStruct & rr](https://github.com/btakita/rr/issues/102) mentioned in old rr repo.
Will `rr` support ruby 2.3.+ or should I find a workaround?

**Comment by kou** [comment]
I've fixed it and released a new version.

**Comment by arthurlm44** [comment]
Thanks @kou !
