### ISSUE TITLE
Support for Rspec 3

### ISSUE THREAD

**Issue by dzikichomik** [rr/rr#65]
Is there a chance that rr will support Rspec version 3?
At present I got strange error: `undefined method 'to_sym' for #<Object:0x00000003f09a30>` when I use Rspec v. 3.4.

**Comment by apohllo** [comment]
To be more specific, that error appears when `rspec-mocks` are loaded. 
When it is not loaded, I've got `undefined method 'stub' for #<RSpec::ExampleGroups...`.

**Comment by kou** [comment]
There is no plan to support RSpec 3.
If we support RSpec 3, we'll create rspec-rr gem instead of implementing RSpec 3 support into rr itself.

**Comment by contentfree** [comment]
Is there a reason the `rspec-rr` gem hasn't been created? It seems like it's mostly just the `adapters/rr_methods.rb` file that was moved to RR::DSL.

**Comment by kou** [comment]
Because nobody doesn't work on it.
If you work on it, I'll create rr/rspec-rr repository for you.

**Comment by punkrats** [comment]
You can make RR work with RSpec by adjusting the configuration. Just replace

`config.mock_with :rr`

by

`config.mock_framework = RR::Integrations::RSpec2::Mixin`

**Comment by punkrats** [comment]
You can make RR work with RSpec 3 by adjusting the configuration. Just replace

`config.mock_with :rr`

by

`config.mock_framework = RR::Integrations::RSpec2::Mixin`

**Comment by pirj** [comment]
We've revived RR support in RSpec, it will presumably be released with RSpec 4.0. https://github.com/rspec/rspec-core/pull/2884

We can't change this dependency in RSpec 3, as this is a breaking change (well, for those using RR 1.0). Users of RR 1.2 and 3.0 are welcome to try pre-release RSpec 4.

RR 1.2 won't be officially supported, as this would require testing against two major versions, and we're not really up to it. But it should work given that [this change](https://github.com/rr/rr/commit/65a29643515575bbde9686c5ccade87f7b2a73df#diff-6aad5729c760c1d242cb39250fe9c9e57a15753e3a347a8413520b3415454e42R56) was done in 1.2 and still stands.

**Comment by kou** [comment]
Thanks for notifying this.
I close this.
