### ISSUE TITLE
Using "yield" in stubbed functions doesn't work

### ISSUE THREAD

**Issue by Hubro** [rr/rr#71]
See the following example:

```ruby
require "minitest/spec"
require "minitest/autorun"
require "rr"

module MyProject
  extend self

  # Convenience method for timing code execution
  def time
    start = Time.new

    yield

    return (Time.new - start)
  end
end

describe "issue with stubbing functions using yield" do
  before {
    stub(MyProject).time {
      yield   # This line crashes with "no block given"
      3.14
    }
  }

  it "doesn't work as expected" do
    x = false

    time = MyProject.time {
      x = true
    }

    assert_equal 3.14, time
    assert_equal true, x
  end
end
```

I'm trying to stub out a function that takes a block, but I need the stub implementation to execute the given block for my code to work. In [your example from the API overview](https://github.com/rr/rr/blob/master/doc/03_api_overview.md#stubbing-method-implementation--return-value), you simply call `yield` inside the stub implementation, but when I try this it crashes with "no block given".

I'm using Ruby 2.5.0 with rr 1.2.1.

Am I doing something wrong here, or is this a bug?

**Comment by kou** [comment]
You can't use `yield` here. Because the `yield` calls block of the current scope not the block `MyProject.time {}`.

For example, the script prints `:a`.

```ruby
require "minitest/spec"
require "minitest/autorun"
require "rr"

module MyProject
  extend self

  # Convenience method for timing code execution
  def time
    start = Time.new

    yield

    return (Time.new - start)
  end
end

describe "issue with stubbing functions using yield" do
  def a
    stub(MyProject).time {
      yield
      3.14
    }
  end

  before {
    a {p :a}
  }

  it "doesn't work as expected" do
    x = false

    time = MyProject.time {
      x = true
    }

    assert_equal 3.14, time
    assert_equal true, x
  end
end
```

This is a specification of Ruby not RR.

You should write the code like the following:

```ruby
stub(MyProject).time {|block|
  block.call
  3.14
}
```

**Comment by Hubro** [comment]
Ah, good call, I didn't know I could yield "through" a block.

I did try this, but it fails with something like `undefined method "call" for nil:NilClass`:

```
stub(MyProject).time { |&block|
    block.call
    3.14
}
```

Unless I've misunderstood, your suggestion requires the block to be explicitly passed as the first argument.

**Comment by kou** [comment]
`&` in `&block` is needless.

**Comment by kou** [comment]
Old Ruby doesn't support "block argument" in `Proc`.
Recent Ruby supports it. So we can support `&block` for now.
