### ISSUE TITLE
How about to update website?

### ISSUE THREAD

**Issue by kachick** [rr/rr#80]
https://github.com/rr/rr/blob/6994e43187e2bb80a856146497ced41063c09437/rr.gemspec#L13 referenced active URL

<img width="700" alt="スクリーンショット 2021-06-09 3 00 37" src="https://user-images.githubusercontent.com/1180335/121236388-db201e00-c8d0-11eb-98b2-5c9a787f0041.png">

But it shows `version 1.0.5`. Looks `gh-pages` branch is not updated in this 8 years https://github.com/rr/rr/blob/65796415efb1407ca56bb365432d14fab2392baa/index.html

<img width="901" alt="スクリーンショット 2021-06-09 3 00 40" src="https://user-images.githubusercontent.com/1180335/121236392-de1b0e80-c8d0-11eb-8844-5e02bd5d8c8b.png">

And this repository information referenced to old URL

<img width="325" alt="スクリーンショット 2021-06-09 3 01 54" src="https://user-images.githubusercontent.com/1180335/121236394-df4c3b80-c8d0-11eb-9633-8e20e47169d4.png">

It is 404 not found 😢 

<img width="750" alt="スクリーンショット 2021-06-09 3 02 02" src="https://user-images.githubusercontent.com/1180335/121236395-dfe4d200-c8d0-11eb-9490-540b736a3310.png">

I think, updating `gh-pages` with GitHub Actions is a useful way now.
But I couldn't find same theme in latest GitHub choices... `https://github.com/{owner_name}/rr/settings/pages/themes?source=gh-pags2&source_dir=%2F`

**Comment by kou** [comment]
> And this repository information referenced to old URL

Fixed.

**Comment by kou** [comment]
> I think, updating `gh-pages` with GitHub Actions is a useful way now.

I've added a GitHub Actions job to update version in the page on new release.
