### ISSUE TITLE
Unable to use RR in `setup` with `Minitest` and `ActiveSupport::TestCase`

### ISSUE THREAD

**Issue by TheDeepestSpace** [rr/rr#87]
First off - thanks for this awesome library, I really enjoy the functionality.

I am using `rr` with Rails, thus inherently the integration adapters that are being loaded are `Minitest` and `MinitestWithActiveSupport`. The issue that I am facing is that my stubs/mocks in `setup { ... }` blocks in concrete `ActiveSupport::TestCase`s are being ignored

### Steps to reproduce

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'minitest', '~> 5'
  gem 'activesupport', '~> 5.2'
  gem 'rr', '~> 3', require: false # see below
end

# done by Rails when running `rails test`
require 'active_support'
require 'active_support/testing/autorun'

# done by me in `test/test_helper.rb`, because otherwise RR will not load the active support adapter
require 'rr'

class Subj
  def self.stub_me; false; end
end

class SubjTest < ActiveSupport::TestCase
  setup { stub(Subj).stub_me { true } }
  test('stub_me') { assert Subj.stub_me }
end

class SubjTest2 < ActiveSupport::TestCase
  test 'stub_me again' do
    stub(Subj).stub_me { true }
    assert Subj.stub_me
  end
end
```
Output:
```
$ ruby bug.rb                                                      
Run options: --seed 13220

# Running:

F.

Finished in 0.007425s, 269.3696 runs/s, 269.3696 assertions/s.

  1) Failure:
SubjTest#test_stub_me [bug.rb:23]:
Expected false to be truthy.

2 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

### Theorizations 

In this situation, `RR.reset` seems to be ran twice for each test case:
1. Run `setup` hook for `ActiveSupport` adapter => `RR.reset`
2. Run `SubjTest`'s `setup`
3. Run `setup_with_rr` for `Minitest` adapter => `RR.reset`  (vaporizes my RR declarations from step 2)

### Workaround

Add this line before declaring concrete test case classes:
```ruby
ActiveSupport::TestCase.class_eval { alias_method :setup, :setup_without_rr }
```

This effectively nullifies the `Minitest` adapter logic.

**Comment by kou** [comment]
Thanks for the detailed report.
It was very helpful.

I've fixed and released a new version.
