### ISSUE TITLE
wildcard_match? method of Hash return false if the hash order changes

### ISSUE THREAD

**Issue by kawamotosatoshi** [rr/rr#94]
I found it when I ran assert_received on test-unit.
Test failed when using "anything" as in the example below.

e.g.
```
  assert_received(@command) { |o| o.call(hash, anything) }
```

If the hash order does not match, it is because the "wildcard_match?" method of Hash returns false.

```
irb(main):002:0> {:a => 1, :b => 2} == {:b => 2, :a => 1}
=> true
irb(main):003:0> {:a => 1, :b => 2}.wildcard_match?({:b => 2, :a => 1})
=> false
```

When using "anything", "exact_match?" method returns false and runs "wildcard_match?".

https://github.com/rr/rr/blob/557eaef4215a9a074118d50df2b65a82154cdf93/lib/rr/recorded_calls.rb#L98-L99

Use the index when checking for matches.
Despite being Hash, the order must match.

https://github.com/rr/rr/blob/557eaef4215a9a074118d50df2b65a82154cdf93/lib/rr/core_ext/hash.rb#L9-L14

**Comment by kawamotosatoshi** [comment]
I suggest the following:

```ruby
class Hash
  def wildcard_match?(other)
    return false unless other.is_a?(Hash)

    return false if keys.size != other.keys.size

    mine = reject {|x|x.respond_to?(:wildcard_match?)}
    mine.each do |(key, value)|
      return false unless other.key?(key)
      if value.respond_to?(:wildcard_match?)
        return false unless value.wildcard_match?(other[key])
      else
        return false unless value == other[key]
      end
    end

    reject { |(key, value)| mine.keys.include?(key) }.zip(other.reject { |(key, value)| mine.keys.include?(key) }).
      each do |(key, value), (other_key, other_value)|
        return false unless key.wildcard_match?(other_key)
        if value.respond_to?(:wildcard_match?)
          return false unless value.wildcard_match?(other_value)
        else
          return false unless value == other_value
        end
      end

    true
  end
end
```

**Comment by kawamotosatoshi** [comment]
I have confirmed that the following is true.
```ruby
{:a => 1, :b => 2, is_a(Symbol) => 3}.wildcard_match?(:c => 3, :b => 2, :a => 1) # => true
```

**Comment by kou** [comment]
Thanks for the suggestion.
But this doesn't work with the following case:

```ruby
```

**Comment by kawamotosatoshi** [comment]
Thank you for the improvement.
I ran assert_received on test-unit and confirmed that it was successful.
