### ISSUE TITLE
Is there a way to get behaviour like `and_call_original`?

### ISSUE THREAD

**Issue by judylovesruby** [rr/rr#95]
Hello,
thanks for creating this library! The syntax looks quite easy and good to use. But I was wondering if there is a way to call the original method after an expectation was met, just like RSpec's `and_call_original` method does? I could not find it in the documentation in the README. 

This is the functionality I miss most when using Minitest with Mocha. And if RR would provide that I would consider to use it instead of Mocha :slightly_smiling_face:

**Comment by kou** [comment]
There is `#implemented_by_original_method` but it's broken now.

Here is an workaround: 

```ruby
require "rr"

class A
  def b(x, y)
    p [x, y]
  end
end

a = A.new
b = a.method(:b)
RR.stub(a).b.implemented_by(b)
RR.stub(a).b(3, 4) {p [:stub, 3, 4]}
a.b(3, 4) # => [:stub, 3, 4]
a.b(1, 2) # => [1, 2]
```

**Comment by kou** [comment]
Ah, sorry. You can use `#proxy`:

```ruby
require "rr"

class A
  def b(x, y)
    p [x, y]
  end
end

a = A.new
RR.stub.proxy(a).b
RR.stub(a).b(3, 4) {p [:stub, 3, 4]}
a.b(3, 4) # => [:stub, 3, 4]
a.b(1, 2) # => [1, 2]
```

**Comment by judylovesruby** [comment]
Thanks a lot for your fast reply! I'm going to try that and see if it fits my use case :slightly_smiling_face: 
(I'm closing the issue now - if I have further questions I can still reopen it)
