### ISSUE TITLE
Support for io_uring

### ISSUE THREAD

**Issue by vchuravy** [rr/rr#97]
I was trying to debug a library using io_uring,
but under `rr` the application switches codepaths to the fallback without `io_uring` I assume that `rr` spoofs the syscall to fail since modeling it correctly would be quite a task.

**Comment by kou** [comment]
I think that https://github.com/rr-debugger/rr was what you want to find. :-)

**Comment by vchuravy** [comment]
Oh gosh... Yes. My brain without Caffeine is not to be trusted apparently.
